//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "customers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[sea_orm(column_name = "uuid")]
    pub contact_uuid: Uuid,
    pub user_name: String,
    pub phone_number: String,
    pub address: Option<String>,
    pub community: Option<String>,
    pub building: Option<String>,
    pub house_area_sqm: Option<i32>,
    pub service_need: Option<String>,
    pub tags: Json,
    pub last_service_at: Option<DateTime<Utc>>,
    pub follow_up_status: String,
    pub creator_uuid: Uuid,
    pub inserted_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
