//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "orders")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: Uuid,
    pub customer_id: Option<Uuid>,
    pub status: String,
    pub amount_cents: i64,
    pub notes: Option<String>,
    pub request_id: Option<Uuid>,
    pub contact_uuid: Option<Uuid>,
    pub assigned_user_uuid: Option<Uuid>,
    pub scheduled_start_at: Option<DateTime<Utc>>,
    pub scheduled_end_at: Option<DateTime<Utc>>,
    pub dispatch_note: Option<String>,
    pub settlement_status: String,
    pub settlement_note: Option<String>,
    pub inserted_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
