//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub use super::contacts::Entity as Contacts;
pub use super::admin_users::Entity as AdminUsers;
pub use super::merchant::Entity as Merchant;
pub use super::users::Entity as Users;
