//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "service_requests")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: Uuid,
    pub contact_uuid: Uuid,
    pub service_content: String,
    pub appointment_start_at: Option<DateTime<Utc>>,
    pub appointment_end_at: Option<DateTime<Utc>>,
    pub status: String,
    pub source: String,
    pub notes: Option<String>,
    pub inserted_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
