//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "system_config_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: Uuid,
    pub category_code: String,
    pub key: String,
    pub label: String,
    pub description: Option<String>,
    pub value_type: String,
    pub default_value: Json,
    pub value: Option<Json>,
    pub validation: Option<Json>,
    pub ui_schema: Option<Json>,
    pub is_required: bool,
    pub is_editable: bool,
    pub is_sensitive: bool,
    pub sort_order: i32,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
