[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[lib]
name = "backend"
path = "src/lib.rs"

[dependencies]
shared = { path = "../shared" }
dotenvy.workspace = true
sea-orm.workspace = true
chrono.workspace = true
rust_xlsxwriter.workspace = true
