use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Customers::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Customers::Uuid)
                            .uuid()
                            .not_null()
                            .primary_key()
                            .default(Expr::cust("gen_random_uuid()")),
                    )
                    .col(ColumnDef::new(Customers::Name).string().not_null())
                    .col(ColumnDef::new(Customers::PhoneNumber).string().null())
                    .col(
                        ColumnDef::new(Customers::Status)
                            .string()
                            .not_null()
                            .default("active"),
                    )
                    .col(ColumnDef::new(Customers::Notes).text().null())
                    .col(
                        ColumnDef::new(Customers::InsertedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(Customers::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(CustomerFollowups::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(CustomerFollowups::Uuid)
                            .uuid()
                            .not_null()
                            .primary_key()
                            .default(Expr::cust("gen_random_uuid()")),
                    )
                    .col(
                        ColumnDef::new(CustomerFollowups::CustomerId)
                            .uuid()
                            .not_null(),
                    )
                    .col(ColumnDef::new(CustomerFollowups::Content).text().not_null())
                    .col(
                        ColumnDef::new(CustomerFollowups::FollowUpAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(CustomerFollowups::InsertedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(CustomerFollowups::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_customer_followups_customer")
                            .from(CustomerFollowups::Table, CustomerFollowups::CustomerId)
                            .to(Customers::Table, Customers::Uuid)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(Employees::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Employees::Uuid)
                            .uuid()
                            .not_null()
                            .primary_key()
                            .default(Expr::cust("gen_random_uuid()")),
                    )
                    .col(ColumnDef::new(Employees::Name).string().not_null())
                    .col(ColumnDef::new(Employees::PhoneNumber).string().null())
                    .col(
                        ColumnDef::new(Employees::Status)
                            .string()
                            .not_null()
                            .default("active"),
                    )
                    .col(ColumnDef::new(Employees::Role).string().null())
                    .col(
                        ColumnDef::new(Employees::InsertedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(Employees::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(Orders::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Orders::Uuid)
                            .uuid()
                            .not_null()
                            .primary_key()
                            .default(Expr::cust("gen_random_uuid()")),
                    )
                    .col(ColumnDef::new(Orders::CustomerId).uuid().not_null())
                    .col(
                        ColumnDef::new(Orders::Status)
                            .string()
                            .not_null()
                            .default("pending"),
                    )
                    .col(
                        ColumnDef::new(Orders::AmountCents)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(ColumnDef::new(Orders::Notes).text().null())
                    .col(
                        ColumnDef::new(Orders::InsertedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(Orders::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_orders_customer")
                            .from(Orders::Table, Orders::CustomerId)
                            .to(Customers::Table, Customers::Uuid)
                            .on_delete(ForeignKeyAction::Restrict),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(Schedules::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Schedules::Uuid)
                            .uuid()
                            .not_null()
                            .primary_key()
                            .default(Expr::cust("gen_random_uuid()")),
                    )
                    .col(ColumnDef::new(Schedules::OrderUuid).uuid().not_null())
                    .col(ColumnDef::new(Schedules::EmployeeId).uuid().not_null())
                    .col(
                        ColumnDef::new(Schedules::StartAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Schedules::EndAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Schedules::Status)
                            .string()
                            .not_null()
                            .default("planned"),
                    )
                    .col(ColumnDef::new(Schedules::Notes).text().null())
                    .col(
                        ColumnDef::new(Schedules::InsertedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(Schedules::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_schedules_order")
                            .from(Schedules::Table, Schedules::OrderUuid)
                            .to(Orders::Table, Orders::Uuid)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_schedules_employee")
                            .from(Schedules::Table, Schedules::EmployeeId)
                            .to(Employees::Table, Employees::Uuid)
                            .on_delete(ForeignKeyAction::Restrict),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(OrderFeedback::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(OrderFeedback::Uuid)
                            .uuid()
                            .not_null()
                            .primary_key()
                            .default(Expr::cust("gen_random_uuid()")),
                    )
                    .col(ColumnDef::new(OrderFeedback::OrderId).uuid().not_null())
                    .col(ColumnDef::new(OrderFeedback::WorkerId).uuid().null())
                    .col(ColumnDef::new(OrderFeedback::Rating).integer().null())
                    .col(ColumnDef::new(OrderFeedback::Content).text().null())
                    .col(
                        ColumnDef::new(OrderFeedback::InsertedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(OrderFeedback::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_order_feedback_order")
                            .from(OrderFeedback::Table, OrderFeedback::OrderId)
                            .to(Orders::Table, Orders::Uuid)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_order_feedback_worker")
                            .from(OrderFeedback::Table, OrderFeedback::WorkerId)
                            .to(Employees::Table, Employees::Uuid)
                            .on_delete(ForeignKeyAction::SetNull),
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(OrderFeedback::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(Schedules::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(Orders::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(Employees::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(CustomerFollowups::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(Customers::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum Customers {
    Table,
    Uuid,
    Name,
    PhoneNumber,
    Status,
    Notes,
    InsertedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum CustomerFollowups {
    Table,
    Uuid,
    CustomerId,
    Content,
    FollowUpAt,
    InsertedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum Employees {
    Table,
    Uuid,
    Name,
    PhoneNumber,
    Status,
    Role,
    InsertedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum Orders {
    Table,
    Uuid,
    CustomerId,
    Status,
    AmountCents,
    Notes,
    InsertedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum Schedules {
    Table,
    Uuid,
    OrderUuid,
    EmployeeId,
    StartAt,
    EndAt,
    Status,
    Notes,
    InsertedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum OrderFeedback {
    Table,
    Uuid,
    OrderId,
    WorkerId,
    Rating,
    Content,
    InsertedAt,
    UpdatedAt,
}
