use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(ServiceRequests::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ServiceRequests::Uuid)
                            .uuid()
                            .not_null()
                            .primary_key()
                            .default(Expr::cust("gen_random_uuid()")),
                    )
                    .col(ColumnDef::new(ServiceRequests::ContactUuid).uuid().not_null())
                    .col(ColumnDef::new(ServiceRequests::ServiceContent).text().not_null())
                    .col(
                        ColumnDef::new(ServiceRequests::AppointmentStartAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ServiceRequests::AppointmentEndAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ServiceRequests::Status)
                            .string()
                            .not_null()
                            .default("new"),
                    )
                    .col(
                        ColumnDef::new(ServiceRequests::Source)
                            .string()
                            .not_null()
                            .default("sales_manual"),
                    )
                    .col(ColumnDef::new(ServiceRequests::Notes).text().null())
                    .col(
                        ColumnDef::new(ServiceRequests::InsertedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(ServiceRequests::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_service_requests_contact")
                            .from(ServiceRequests::Table, ServiceRequests::ContactUuid)
                            .to(Contacts::Table, Contacts::ContactUuid)
                            .on_delete(ForeignKeyAction::Restrict),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Orders::Table)
                    .modify_column(ColumnDef::new(Orders::CustomerId).uuid().null())
                    .add_column_if_not_exists(ColumnDef::new(Orders::RequestId).uuid().null())
                    .add_column_if_not_exists(ColumnDef::new(Orders::ContactUuid).uuid().null())
                    .add_column_if_not_exists(ColumnDef::new(Orders::AssignedUserUuid).uuid().null())
                    .add_column_if_not_exists(
                        ColumnDef::new(Orders::ScheduledStartAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .add_column_if_not_exists(
                        ColumnDef::new(Orders::ScheduledEndAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .add_column_if_not_exists(ColumnDef::new(Orders::DispatchNote).text().null())
                    .add_column_if_not_exists(
                        ColumnDef::new(Orders::SettlementStatus)
                            .string()
                            .not_null()
                            .default("unsettled"),
                    )
                    .add_column_if_not_exists(ColumnDef::new(Orders::SettlementNote).text().null())
                    .to_owned(),
            )
            .await?;

        manager
            .create_foreign_key(
                ForeignKey::create()
                    .name("fk_orders_request")
                    .from(Orders::Table, Orders::RequestId)
                    .to(ServiceRequests::Table, ServiceRequests::Uuid)
                    .on_delete(ForeignKeyAction::SetNull)
                    .to_owned(),
            )
            .await?;
        manager
            .create_foreign_key(
                ForeignKey::create()
                    .name("fk_orders_contact")
                    .from(Orders::Table, Orders::ContactUuid)
                    .to(Contacts::Table, Contacts::ContactUuid)
                    .on_delete(ForeignKeyAction::Restrict)
                    .to_owned(),
            )
            .await?;
        manager
            .create_foreign_key(
                ForeignKey::create()
                    .name("fk_orders_assigned_user")
                    .from(Orders::Table, Orders::AssignedUserUuid)
                    .to(Users::Table, Users::Uuid)
                    .on_delete(ForeignKeyAction::SetNull)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_service_requests_status")
                    .table(ServiceRequests::Table)
                    .col(ServiceRequests::Status)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_service_requests_appointment_start_at")
                    .table(ServiceRequests::Table)
                    .col(ServiceRequests::AppointmentStartAt)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_service_requests_contact")
                    .table(ServiceRequests::Table)
                    .col(ServiceRequests::ContactUuid)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_orders_status")
                    .table(Orders::Table)
                    .col(Orders::Status)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_orders_scheduled_start_at")
                    .table(Orders::Table)
                    .col(Orders::ScheduledStartAt)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_orders_assigned_user")
                    .table(Orders::Table)
                    .col(Orders::AssignedUserUuid)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_orders_contact")
                    .table(Orders::Table)
                    .col(Orders::ContactUuid)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_orders_request")
                    .table(Orders::Table)
                    .col(Orders::RequestId)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_index(
                Index::drop()
                    .name("idx_orders_request")
                    .table(Orders::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_index(
                Index::drop()
                    .name("idx_orders_contact")
                    .table(Orders::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_index(
                Index::drop()
                    .name("idx_orders_assigned_user")
                    .table(Orders::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_index(
                Index::drop()
                    .name("idx_orders_scheduled_start_at")
                    .table(Orders::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_index(
                Index::drop()
                    .name("idx_orders_status")
                    .table(Orders::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_index(
                Index::drop()
                    .name("idx_service_requests_contact")
                    .table(ServiceRequests::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_index(
                Index::drop()
                    .name("idx_service_requests_appointment_start_at")
                    .table(ServiceRequests::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_index(
                Index::drop()
                    .name("idx_service_requests_status")
                    .table(ServiceRequests::Table)
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Orders::Table)
                    .drop_column(Orders::SettlementNote)
                    .drop_column(Orders::SettlementStatus)
                    .drop_column(Orders::DispatchNote)
                    .drop_column(Orders::ScheduledEndAt)
                    .drop_column(Orders::ScheduledStartAt)
                    .drop_column(Orders::AssignedUserUuid)
                    .drop_column(Orders::ContactUuid)
                    .drop_column(Orders::RequestId)
                    .to_owned(),
            )
            .await?;

        manager
            .drop_table(Table::drop().table(ServiceRequests::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum ServiceRequests {
    Table,
    Uuid,
    ContactUuid,
    ServiceContent,
    AppointmentStartAt,
    AppointmentEndAt,
    Status,
    Source,
    Notes,
    InsertedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum Orders {
    Table,
    CustomerId,
    RequestId,
    ContactUuid,
    AssignedUserUuid,
    ScheduledStartAt,
    ScheduledEndAt,
    DispatchNote,
    SettlementStatus,
    SettlementNote,
    Status,
}

#[derive(DeriveIden)]
enum Contacts {
    Table,
    ContactUuid,
}

#[derive(DeriveIden)]
enum Users {
    Table,
    Uuid,
}
