//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "contacts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub contact_uuid: Uuid,
    pub user_name: String,
    pub company: String,
    pub position: String,
    pub phone_number: String,
    pub email: String,
    pub last_contact: DateTime,
    pub value_level: i32,
    pub creator_uuid: Uuid,
    pub status: i32,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
